version: '3'

services:
  backend:
    build: 
      context: "./testify-server"
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - './testify-server/.env'
  client:
    build: 
      context: "./testify-client/"
    command: node server.js
    ports:
      - "3000:3000"
  nginx:
    build:
      context: "./nginx/"
    ports:
      - "80:8080"
    depends_on:
      - backend
      - client